<?php require_once '../database.php';
require_once '../functions.php';

$facilities = (getFacilities());
$employees = (getEmployees());

// Execute query if not empty
if (!empty($query)) {
  $statement = $conn->prepare($query);
  if($statement->execute()) {
    $data = $statement->fetchAll(PDO::FETCH_ASSOC);
  } else {
    header("Location: ./failure.php");
  }
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../styles.css">
  <script src="https://kit.fontawesome.com/6ebd7b3ed7.js" crossorigin="anonymous"></script>
  <script>
    // Show/hide divs based on query selection
    function showDiv(select) {
      //show the employee selector
      if (select.value == "q10") {
        document.getElementById('hidden_employees').style.display = "block";
        document.getElementById('hidden_facilities').style.display = "none";
      } 
      //show the facilities selector
      else if ((select.value == "q9") || (select.value == "q12") || (select.value == "q13") || (select.value =="q14")) {
        document.getElementById('hidden_employees').style.display = "none";
        document.getElementById('hidden_facilities').style.display = "block";
      } 
      //hide both selectors
      else {
        document.getElementById('hidden_employees').style.display = "none";
        document.getElementById('hidden_facilities').style.display = "none";
      }
    }
  </script>
  <title>Custom Queries</title>
</head>
<body>
  <?php include_once ('../navbar.php'); ?>
  <div class="containerLeftMargin">
    <h2>Choose a custom query to execute from the dropdown below.</h2>

    <!-- Dynamic form showing list of queries and needed parameters as necessary. -->
    <form action="./processCustom.php" method="post">
      <select name="query" id="query" onchange="showDiv(this);">
        <option value="invalid" default>Choose One</option>
        <option value="q8">Q8. Get details of all facilities in the system.</option>
        <option value="q9">Q9. Get details of all the employees currently working in a specific facility.</option>
        <option value="q10">Q10. For a given employee, get the details of all the schedules she/he has been scheduled during a specific period of time.</option>
        <option value="q11">Q11. Get details of all the teachers who have been infected by COVID-19 in the past two weeks.</option>
        <option value="q12">Q12. List the emails generated by a given facility.</option>
        <option value="q13">Q13. For a given facility, generate a list of all the teachers who have been on schedule to work in the last two weeks.</option>
        <option value="q14">Q14. For a given facility, give the total hours scheduled for every teacher during a specific period.</option>
        <option value="q15">Q15. For every high school, provide data on COVID-19 infections.</option>
        <option value="q16">Q16. For every ministry in the system, provide its details.</option>
        <option value="q17">Q17. For every ministry in the system, provide its minister's details.</option>
      </select>
      <br/>
      <select id="hidden_employees" name="employee" default="" required>
        <?php foreach ($employees as $employee) { ?>
          <?php $record = $employee['PersonID'] . ' - ' . $employee['FirstName'] . ' ' . $employee['LastName']?>
          <option value="<?= $employee['PersonID'] ?>"><?= $record ?></option>
        <?php } ?>
      </select>
      <select id="hidden_facilities" name="facility" default ="" required>
        <?php foreach ($facilities as $facility) { ?>
          <?php $record = $facility['FacilityID'] . ' - ' . $facility['Name'] ?> 
          <option value="<?= $facility['FacilityID'] ?>"><?= $record ?></option>
        <?php } ?>
      </select>
      <br/>
      <button class="submitBtn" type="submit">Submit</button>
    </form>

    <button class="smallBtn" onclick="history.back()">Return to Previous Page</button>
  </div>
</body>
</html>