<?php require_once '../database.php';
require_once '../functions.php';

if(isset($_GET["query"]))  {
  $query = $_GET["query"];
} else {
  $query = "";
}

// SQL queries
switch ($query) {
  case "invalid":
    echo '<script>alert("Invalid choice.")</script>';
    $query = "";
    break;
  case "q8":
    $query = "SELECT * FROM facilities"; //sample only, not the correct query
    break;
  case "q9":
    $query = "";
    break;
  case "q10":
    $query = "";
    break;
  case "q11":
    $query = "";
    break;
  case "q12":
    $query = "";
    break;
  case "q13":
    $query = "";
    break;
  case "q14":
    $query = "";
    break;
  case "q15":
    $query = "";
    break;
  case "q16":
    $query = "";
    break;
  case "q17":
    $query = "";
    break;
  case "q18":
    $query = "";
}

// Execute query if not empty
if (!empty($query)) {
  $statement = $conn->prepare($query);
  $statement->execute();
  $data = $statement->fetchAll(PDO::FETCH_ASSOC);
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../styles.css">
  <script src="https://kit.fontawesome.com/6ebd7b3ed7.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/gh/akjpro/form-anticlear/base.js"></script>
  <script>
    // Show/hide divs based on query selection
    function showDiv(select) {
      if (select.value == "q10") {
        document.getElementById('hidden_employees').style.display = "block";
        document.getElementById('hidden_facilities').style.display = "none";
      } 
      else if ((select.value == "q13") || (select.value =="q14")) {
        document.getElementById('hidden_employees').style.display = "none";
        document.getElementById('hidden_facilities').style.display = "block";
      } 
      else {
        document.getElementById('hidden_employees').style.display = "none";
        document.getElementById('hidden_facilities').style.display = "none";
      }
    }
  </script>
  <title>Custom Queries</title>
</head>
<body>
  <?php include_once ('../navbar.php'); ?>
  <div class="containerLeftMargin">
    <h2>Choose a custom query to execute from the dropdown below.</h2>

    <!-- Dynamic form showing list of queries and needed parameters as necessary. -->
    <form class="form-anticlear" action="../covid/custom.php" method="get">
      <select name="query" id="query" onchange="showDiv(this);">
        <option value="invalid" default>Choose One</option>
        <option value="q8">Q8. Get details of all facilities in the system.</option>
        <option value="q9">Q9. Get details of all the employees currently working in a specific facility.</option>
        <option value="q10">Q10. For a given employee, get the details of all the schedules she/he has been scheduled during a specific period of time.</option>
        <option value="q11">Q11. Get details of all the teachers who have been infected by COVID-19 in the past two weeks.</option>
        <option value="q12">Q12. List the emails generated by a given facility.</option>
        <option value="q13">Q13. For a given facility, generate a list of all the teachers who have been on schedule to work in the last two weeks.</option>
        <option value="q14">Q14. For a given facility, give the total hours scheduled for every teacher during a specific period.</option>
        <option value="q15">Q15. For every high school, provide data on COVID-19 infections.</option>
        <option value="q16">Q16. For every ministry in the system, provide its details.</option>
        <option value="q17">Q17. For every ministry in the system, provide its minister's details.</option>
        <option value="q18">Q18. Get details of the counselor(s) who are currently working and has been infected by COVID-19 at least three times.</option>
      </select>
      <select id="hidden_employees" name="employee">
        <p>Choose an employee:</p>
        <option value="">An employee</option>
      </select>
      <select id="hidden_facilities" name="facility">
        <p>Choose a facility:</p>
        <option value="">A facility</option>
      </select>
      <input type="submit" value="Submit">
    </form>

    <!-- Displays data from the selected custom query -->
    <?php if (!empty($data)) { ?>
    <table class="styled-table">
    <thead>
      <tr>
        <?php foreach ($data[0] as $key => $value) { ?>
          <td><?= $key?></td>
        <?php } ?>
        <?php unset($key); ?>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($data as $row) { ?>
        <tr>
          <?php foreach ($row as $key => $value) { ?>
            <td><?= $value; ?></td>
          <?php } ?>
        </tr>
      <?php } ?>
    </tbody>
    </table>
    <?php } ?>

    <button class="smallBtn" onclick="history.back()">Return to Previous Page</button>
  </div>
</body>
</html>